build-stage:
  stage: build
  image: gitlab-registry.cern.ch/ci-tools/ci-worker:cc7
  before_script:
    - echo "Start installations"
    - yum install -y ruby
    - sudo -u nobody bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    - brew install hugo
  script:
    - hugo
  artifacts:
    paths:
    - public
  only:
    - master