build-stage:
  stage: build
  image: gitlab-registry.cern.ch/ci-tools/ci-worker:cc7
  before_script:
    - yum install -y ruby
    - ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    - brew install hugo
  script:
    - hugo
  artifacts:
    paths:
    - public
  only:
    - master