build-stage:
  stage: build
  # All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
  image: registry.gitlab.com/pages/hugo:latest
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - hugo
    - echo "done!!"
  artifacts:
    paths:
    - public
  only:
    - master


deploy-stage:
  stage: deploy
  variables:
    #"EOS_PATH": "/eos/user/a/atlasout/www"
    "EOS_PATH": "/eos/user/a/atlasout/www/new"
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer
  script:
    - deploy-eos
  dependencies:
    - build-stage
  only:
    - master
