name = "ATLAS Open Data - Hugo"
license = "MIT"
licenselink = "https://github.com/atlas-outreach-data-tools/website-hugo-framework/blob/master/themes/hugo-refresh/LICENSE"
description = "ATLAS Open Data from Roberto Jordaney template --> A re-adaptation of the Hugo Fresh theme"
homepage = "https://github.com/atlas-outreach-data-tools"
tags = ["responsive", "blog", "light", "clean", "personal", "multilingual", "syntax-highlighting"]
features = ["blog", "responsive", "simple", "404", "mathjax"]
min_version = "0.45"

[author]
  name = "ATLAS Open Data"
  homepage = "http://opendata.atlas.cern"
